steps:
  # 1. Build and package the Spring Boot JAR
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']

  # 2. Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:latest'
      - '.'

  # 3. Push Docker Images to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:latest']

  # 4. Trigger Remote SSH Deployment on VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh bashasoft304@ems-backend-vm \
          --zone=us-central1-a \
          --command="docker network create ems-network || true && docker pull us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:latest && docker stop department-backend || true && docker rm department-backend || true && docker run -d --name department-backend --network ems-network -p 8081:8081 us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:latest"

images:
  - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/prefab-lamp-498812-u8/ems-repo/department-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
